#!/usr/bin/env python2
"""Provides a GUI interface to install and update PND applications."""


from optparse import OptionParser
from pndstore import options

parser = OptionParser()
parser.add_option('--working-dir', '-w',
    dest='working_dir', default=None,
    metavar='DIRECTORY', help=
    'find/store config and database in DIRECTORY [default: %s]'
    % options.working_dir)
opts, args = parser.parse_args()

if opts.working_dir is not None:
    options.working_dir = opts.working_dir

from pndstore_gui import PNDstore
import gtk

p = PNDstore()
gtk.main()
